"""add_cover_image_to_article

Revision ID: f468afac6d94
Revises: b81bd6ec2918
Create Date: 2026-05-09 17:17:33.702273

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f468afac6d94'
down_revision: Union[str, Sequence[str], None] = 'b81bd6ec2918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'cover_image')
    # ### end Alembic commands ###
